require "biblio_refs/version"
require "biblio_refs/referencia"
require "biblio_refs/list"
require "biblio_refs/publicaciones_periodicas"
require "biblio_refs/articulo_revista"
require "biblio_refs/articulo_periodico"
require "biblio_refs/documento_electronico"
require "biblio_refs/lista_apa"
